language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - gradle clean
  - if [ "$TRAVIS_BRANCH" = "master" ]; then gradle build -PbranchTests=junit.**; fi
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then gradle build -PbranchTests=junit.**; fi
  - if [ "$TRAVIS_BRANCH" = "irene" ]; then gradle build -PbranchTests=junit.irene.*; fi
  - if [ "$TRAVIS_BRANCH" = "jendoliver" ]; then gradle build -PbranchTests=junit.jendoliver.*; fi
  - if [ "$TRAVIS_BRANCH" = "magner" ]; then gradle build -PbranchTests=junit.magner.*; fi
  - if [ "$TRAVIS_BRANCH" = "raikish" ]; then gradle build -PbranchTests=junit.raikish.*; fi