language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; gradle build -PbranchTests=junit.**; fi
  - if [ "$TRAVIS_BRANCH" = "develop" ]; gradle build -PbranchTests=junit.**; fi
  - if [ "$TRAVIS_BRANCH" = "irene" ]; gradle build -PbranchTests=junit.irene.*; fi
  - if [ "$TRAVIS_BRANCH" = "jendoliver" ]; gradle build -PbranchTests=junit.jendoliver.*; fi
  - if [ "$TRAVIS_BRANCH" = "magner" ]; gradle build -PbranchTests=junit.magner.*; fi
  - if [ "$TRAVIS_BRANCH" = "raikish" ]; gradle build -PbranchTests=junit.raikish.*; fi