package model;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import globals.Configuration;
import model.Request.HourFrame;

/**
 * 
 * This class receives a well-formatted RequestList generated by model.parsers.ParserRequests
 * 
 * Recibe RequestList bien formateado del ParserRequests para validar:
 * 
 *  - Que los RequestDays de cada request tengan sentido respecto a la franja de dias de la misma
 *  - Que no se solapen request, si hay una request en el month
 * 
 * @author Jandol
 * @author Raikish
 *
 */
public class RequestPoliceman 
{
	private Map<String, RoomSchedule> roomSchedules = new HashMap<>();
	
	public RequestPoliceman() { }
	
	public Map<String, RoomSchedule> getRoomSchedules() 
	{
		return roomSchedules;
	}
	
	public void process(RequestList list)
	{	
		for(Request request : list)
		{
			// Si los RequestDays de la request tienen sentido respecto a la franja de dias de la misma
				if(isExistingRoom(request.roomName))
					processRequestOnSchedule(request, roomSchedules.get(request.roomName));
				else
					processRequestOnSchedule(request, roomSchedules.put(request.roomName, new RoomSchedule()));
		}
	}

	private void processRequestOnSchedule(Request request, RoomSchedule schedule) 
	{
		// TESTME
		for(int day : getExactDays(request))
		{
			for(HourFrame hourFrame : request.hourFrames)
			{
				for(int hour = hourFrame.startHour; hour < hourFrame.endHour; hour++)
				{
					if(schedule.isEmptyHourFrame(day, hour))
					{
						Map<Integer, Request> dayHours = schedule.get(day);
						dayHours.put(hour, request);
					}
					else
					{
						// TODO log incompatible request (already reserved)
					}
				}
			}
		}
	}
	
	private List<Integer> getExactDays(Request request)
	{
		List<Integer> exactDays = new ArrayList<>();
		Calendar calendar = Calendar.getInstance();
		calendar.set(Calendar.MONTH, Integer.parseInt(Configuration.MONTH_TO_PROCESS));
		// TODO finish
		for(int i = 1; i <= 4; i++)
		{
			calendar.set(Calendar.WEEK_OF_MONTH, i);
			for(RequestDays requestDay : request.requestedDays)
			{
				calendar.set(Calendar.DAY_OF_WEEK, requestDay.ordinal());
				int day = calendar.get(Calendar.DAY_OF_MONTH);
				if(day >= request.dayFrame.startDay && day <= request.dayFrame.endDay)
					exactDays.add(day);
			}
		}
		return exactDays;
	}
	
	// NOTE: Case-sensitive
	private boolean isExistingRoom(String roomName) 
	{
		return roomSchedules.containsKey(roomName);
	}
}
